### ISSUE TITLE
Import dataset

### ISSUE THREAD

**Issue by vlad309523** [ukitgroup/mass-labeling#1]
## Описание формата

Входной файл является `zip` архивом. Структура:

* `screenshots`
	* `http____site.com.jpg`
	* ...
* `out.json`

### out.json

Файл `out.json` состоит из массива элементов `item`. Структура:

```
item{
	"url"           : str,      // "http://site.com"
	"screenshot"    : str,      // "screenshots/http____site.com.jpg"
}
```

**Comment by RomanSteinberg** [comment]
fixed
