### ISSUE TITLE
Instructions page abcent

### ISSUE THREAD

**Issue by RomanSteinberg** [ukitgroup/mass-labeling#10]
User (not admin) main page has link to instructions.html, but markup page has no link to it.

Fixes:
* [x] page url "markup" should be renamed to "assessment";
* [x] mentioned page should have link to instructions.html.

**Comment by v3il** [comment]
Done, https://github.com/ukitgroup/mass-labeling/commit/92c59a335b645477c03214436065bef6632f4102,  https://github.com/ukitgroup/mass-labeling/commit/b0ebe1e403c1ce3c54e9df228a22bf9132e5c849
