### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by RomanSteinberg** [ukitgroup/mass-labeling#11]
Improvements:

* [x] "open slider" button should not work if slider is not generated;
* [x] slider should use multilanguage support;
* [x] investigate the way to provide model rates from outside the system. May be fix it or remove, but as for right now it is supposed unusable.

**Comment by RomanSteinberg** [comment]
So, now we know that we need to 
* [ ] make `cli` command to load model rates to show them on slider.

**Comment by v3il** [comment]
1. https://github.com/ukitgroup/mass-labeling/commit/3092410f14fc501d741de207e4d32a0b45a30504

- When user has no answers yet, 'Generate slider' button is disabled
- When user has no sliders yet, 'Open slider' button is disabled

**Comment by v3il** [comment]
2. https://github.com/ukitgroup/mass-labeling/commit/a0bea06f3728e670e1688ad86c800ca6bfa853e7

Also added the button to navigate back to settings page https://prnt.sc/knsasz

**Comment by v3il** [comment]
3. https://github.com/ukitgroup/mass-labeling/commit/a286dc430f3bae26b511a7f1e53f183af27a428a

A new property `cliImport.modelScoreIn` was added to the configuration, which indicates where the file with model scores is located. By default, its value is `data/import/modelScore.json`, but you can change it on the settings page (/config#tab=tech).

Command Syntax:
`bin/cli import:modelScore | npx bunyan`

You can also use the optional command parameter: `--in` to specify the path of the file outside the project's directory:
`bin/cli import:modelScore --in '/home/User/Desktop/modelScore.json' | npx bunyan`
