### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by RomanSteinberg** [ukitgroup/mass-labeling#13]
It is necessary to implement tasks functionality in the project. Task should have the following properties:
* tasks should be created on Assessment options page;
* each task has user assessment limit, random selection flag and datasets allowed properties;
* only one task could be active at once;
* it could be possible to select another task as active;
* all rates which were made should be linked to current active task;

It will allow Mass Labeling to show progress of each assessor for the active task. It will also allows users to have independent progress counters (number of screenshots rated) for each task.

**Comment by v3il** [comment]
Broken sites, anomalies, local anomalies, stat counters retrieve from current task now
Users unnable to rate any site if there is no active task

It is unable to deactivate datasets from which any site was rated.
Assessment limit can not be less than max count of user's rates of this task.
