### ISSUE TITLE
Settings page "Assessment"

### ISSUE THREAD

**Issue by RomanSteinberg** [ukitgroup/mass-labeling#14]
Improvements:
* [x] "select all" and "deselect all" buttons should have icons instead of text;
* [x] instructions editor should have roll up and roll down buttons only;
* [x] instructions editor should save its content together with other options when "save" button pressed.

**Comment by v3il** [comment]
1. https://github.com/ukitgroup/mass-labeling/commit/ee275b7c6286536d64ce50a7fdf55299add05f41

https://prnt.sc/knsuwb

**Comment by v3il** [comment]
2, 3. https://github.com/ukitgroup/mass-labeling/commit/c2ddb37545725bbe77059373f886aa0d803d5f65

**Comment by RomanSteinberg** [comment]
done
