### ISSUE TITLE
View screenshots deterministically

### ISSUE THREAD

**Issue by RomanSteinberg** [ukitgroup/mass-labeling#5]
Now Mass Labeling supports demonstration of images according to random uniform distribution, which is useful when it is necessary to collect rates of different assessors several times per image per assessor. But  there are some assessment tasks which imply that assessor should look at each image only once. 

We need to make an option to turn on and off random demonstration. It should be on Assessment settings page. When random is on, the 'Max labels per user' should influence the upper limit of screenshots to be viewed. When random is off, the 'Max labels per user' should be dissabled too and each screenshot should be shown exactly once.

**Comment by v3il** [comment]
Done, https://prnt.sc/kiv6ds
Checkbox is checked by default. Value is saved in config.json (added as new property)

**Comment by RomanSteinberg** [comment]
We need to unite Admin and Assessment options pages. And 'User assessments limit' option should be close to 'Random selection' (show_random).

**Comment by v3il** [comment]
Done, https://prnt.sc/kll9sq

**Comment by RomanSteinberg** [comment]
This part
> When random is on, the 'Max labels per user' should influence the upper limit of screenshots to be viewed. When random is off, the 'Max labels per user' should be dissabled too and each screenshot should be shown exactly once.

is not working.

**Comment by RomanSteinberg** [comment]
Also, screenshots limit should be equal to screenshots number in active datasets. [This](http://i.imgur.com/1iHZcak.png) is incorrect.
