### ISSUE TITLE
Instructions page edit

### ISSUE THREAD

**Issue by RomanSteinberg** [ukitgroup/mass-labeling#8]
Instructions is an html file (public/instructions.html) which all assessors can see but administrator can edit it only from server. It will be much more user-freindly if we provide the tool to edit it from web-interface. It should be designed like some multiline edit control prefilled with current instructions text. The button to start edit process should be on Assessment tab of Settings page.

Also, it could be Markdown instaead of pure html. It is up to developer.

**Comment by v3il** [comment]
Done, https://prnt.sc/kcowhq
